### PR TITLE
Add section regarding automated Java bytecode deobfuscation

### PR DESCRIPTION
**Pull request by Col-E**
The article initially states:

> Automated bytecode obfuscation makes reverse-engineering a program difficult and economically unfeasible.

In some cases a majority of the complex work can be automated. So I included a brief section with links to some tools capable of this.

### CODE REVIEW

**Comment by kingthorin** [comment]
That statement is likely quite old, if you feel it is inaccurate please don’t hesitate to edit it.

**Comment by kingthorin** [comment]
For the tool descriptions is there a word or phrase that would be better than ‘commercial’? ‘common’ or ______ ?

**Comment by Col-E** [comment]
Yeah, could probably swap it out for `common`

**Comment by Col-E** [comment]
Swapped it out for `common` and also updated the description since now there are links to tools that can automate most of the process.

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
