### PR TITLE
Update api-tools.yml

### PR DESCRIPTION
**Pull request by apisecuniversity-dave**
add APIsec Scan and APIsec Scan for CI/CD tools

### CODE REVIEW

**Comment by kingthorin** [comment]
I'm sure there are others on the list that already have multiple entries, but there's no award for having the most. Is it really necessary to have you in here 3 times?

@mtesauro thoughts on this? 🤷‍♂️

**Comment by mtesauro** [comment]
@kingthorin I don't think having multiple entries actually adds value to the OWASP & broader community. If anything, it complicates a page I created to try to help simplify things for those looking at API Security tools.

Since these are all from the same vendor/company, perhaps they should reconsider how they listed their entry instead.

The net is, I don't think this PR makes the page better and possibly makes it worse/more confusing.

If there are vendors/companies/projects with multiple listings, then we have some clean-up work to do IMHO.

**Comment by kingthorin** [comment]
Thanks @mtesauro 

@apisecuniversity-dave do you think you could put some effort into combining the 3 entries or that whatever site/page you refer people to then covers all 3?

**Comment by apisecuniversity-dave** [comment]
Thanks for the feedback all, I will come up with an alternate approach like the one @kingthorin suggested

**Pull request closed without merging**
