### PR TITLE
Updated the GrammaTech listing

### PR DESCRIPTION
**Pull request by wcapitani-gt**
removed the company name from product name, and updated the alphabetical position in the list.

### CODE REVIEW

**Comment by kingthorin** [comment]
A single entry seems sufficient.

**Comment by wcapitani-gt** [comment]
> e

Yes, I just wanted to remove the company name (GrammaTech) from the existing listing and reposition the listing alphabetically in the list  -is that not what the commits show?

**Comment by wcapitani-gt** [comment]
I see what happened now, I've fixed it.

**Comment by kingthorin** [comment]
Closer, it shows one addition now, but it should be removing the older entry and should exclude the .DS_Store file

**Comment by wcapitani-gt** [comment]
Hi - trying to fix this, not sure what I've actually accomplished at this point.

**Comment by kingthorin** [comment]
You're getting closer, the .DS_Store is gone now.

If you can confirm your end goal is to remove the original Grammatech entry and replace with CodeSentry I don't mind taking care of it. Just let me know.

**Comment by wcapitani-gt** [comment]
That is exactly my intention - replace the 'GrammaTech CodeSentry' with the 'CodeSentry' entry.  Thanks so much for your help.

**Comment by kingthorin** [comment]
Okay, no problem I'll tackle it.

**Comment by kingthorin** [comment]
There you go, if you could just double check. I'll approve and merge.

**Comment by wcapitani-gt** [comment]
@kingthorin yes that's perfect thanks so much.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
