### PR TITLE
Migrate Ransomware Guide Pages (Spanish)

### PR DESCRIPTION
**Pull request by seguinfo**
Migration of this guide to the new owasp site.

https://wiki.owasp.org/index.php/Gu%C3%ADa_para_evitar_infecciones_de_RANSOMWARE
https://owasp.org/www-pdf-archive/Guia_Contra_Ransomware.pdf

### CODE REVIEW

**Comment by kingthorin** [comment]
Please rebase current and address conflicts.

**Comment by kingthorin** [comment]
Please rebase current and address conflicts.

**Comment by seguinfo** [comment]
Hi

Please, could you rebase this project to https://owasp.org/www-community/
Thank you.

--
Lic. Cristian Borghello, CISSP - CCSK - MVP
Director Segu-Info - Segu-Kids - Antiphishing - ODILA

**Comment by kingthorin** [comment]
This PR doesn't seem to actually do anything it claims to do.

Per the repo readme you should delete your fork, re-fork, and re-clone then submit your PR from a proper state: https://github.com/OWASP/www-community#2020-july-02-please-re-fork-and-re-clone

I searched this PR for the mentioned PDF and RANSOMWARE content and don't see it.

**Comment by kingthorin** [comment]
@seguinfo do you plan to fix this PR or should it just be closed?

**Comment by kingthorin** [comment]
Closing. It's been a month with no helpful response or rework of this pull request 😢

**Pull request closed without merging**
