### PR TITLE
add blacklock security

### PR DESCRIPTION
**Pull request by knassar702**
more info: https://blacklock.io

### CODE REVIEW

**Comment by kingthorin** [comment]
https://github.com/OWASP/www-community/blob/master/tools_schema.json

**Comment by knassar702** [comment]
hey @kingthorin can I add `PTaas` to type list of your json schema?

**Comment by kingthorin** [comment]
You could but it won't be displayed anywhere :wink:

Is it more of a Network level tool than Web?

**Comment by knassar702** [comment]
ohh then how I can i display it please?

+ more of a Web level not Network*

**Comment by kingthorin** [comment]
Wouldn't it be considered a DAST then?

**Comment by kingthorin** [comment]
Quickly skimming the site it reads like a DAST.

**Comment by knassar702** [comment]
hey @kingthorin I change it to DAST can you check

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
