### PR TITLE
Close #120, broken links for application testing

### LINKED ISSUE #120: FAQ SQL injection training link dead
Regarding www-community/pages/OWASP_Application_Security_FAQ.md 
Under the [Where can I try out my testing skills....](https://github.com/OWASP/www-community/blob/master/pages/OWASP_Application_Security_FAQ.md#where-can-i-try-out-my-testing-skills-is-there-a-sample-application-i-can-practice-with) heading is this link: http://www.hackingzone.org/sql/index.php which redirects to a dead page.

### PR DESCRIPTION
**Pull request by ADubhlaoich**
I updated the specific question/heading mentioned in the issue; I started working on also updating the initial two questions but realised I could be working on the page for a literal month and still be nowhere near finishing.

Unless there's objections I'm probably going to periodically take stabs at the page again, as a lot of it could do with a proper re-write but it is a gargantuan project in itself due to the sheer amount of content people added to it over the years.

Fixes OWASP/www-community#120

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks, will review tomorrow.

**Comment by ADubhlaoich** [comment]
I thought having the keyword and number in the PR title would be enough to trigger the automatic linked issues. Good to know it should be in the accompanying text for the future!

**Comment by ADubhlaoich** [comment]
Any movement on this? I'm unsure if I should continue working on the rest of the page, on the chance I'm going astray.

**Comment by kingthorin** [comment]
HI @ADubhlaoich thanks for poking me. I'll try to get this reviewed ASAP.

**Pull request merged**
