### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by ricardosupo**

### CODE REVIEW

**Comment by kingthorin** [comment]
What’s the point of this PR? Chapters each have their own project/page.

**Comment by ricardosupo** [comment]
The chapters in Brazil organize joint events such as OWASP LATAM@home version Portuguese, and we want to have a site where we can centralize the information to redirect to each chapter website, a single place where all can see the activities of all the chapters in Brazil (conference and workshops)

**Comment by ricardosupo** [comment]
In Brasil we have 13 chapters

**Comment by kingthorin** [comment]
I'd suggest that you set it up similar to what Germany has with their "stammtische":
https://owasp.org/www-chapter-germany/stammtische/
https://github.com/OWASP/www-chapter-germany

If you need an equivalent of www-chapter-germany (ex: www-chapter-brazil) setup then reach out to the Chapters Committee (https://owasp.org/www-committee-chapter/) or Harold Blankenship .

**Pull request closed without merging**
