### PR TITLE
Update File Application_Security_Tools

### PR DESCRIPTION
**Pull request by tartamar**
Add Faraday Open Source Tool in Free_for_Open_Source_Application_Security_Tools.md file

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
You seem to have added this to the wrong section

**Comment by tartamar** [comment]
> You seem to have added this to the wrong section

thanks for the answer, what would be the appropriate section?

**Comment by kingthorin** [comment]
I’m not so sure it fits into this page at all. We don’t really have content for misc dashboards or ticketing systems.

**Comment by tartamar** [comment]
I understand, thanks for the feedback. From my point of view I suggested it because I think that I could enter that section:
- It's an Open Source tool for Application Security
- Like Gitlab (which is mentioned), it integrates with CI with DAST, SAST tools, etc.
- Although it has a dashboard, it's API-First, being able to centralize and automate tasks without using the GUI.

**Comment by kingthorin** [comment]
Alright let’s leave it as-is.

Maybe I’m over thinking or not familiar enough.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
