### PR TITLE
tools: rename ScanMyCode to Betterscan

### PR DESCRIPTION
**Pull request by noraj**
the product and repository have been renamed

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Thanks, could you move it to the appropriate location, keeping the entries alphabetic?

**Comment by noraj** [comment]
> Thanks, could you move it to the appropriate location, keeping the entries alphabetic?

Seems it is not ordered alphabetically https://github.com/OWASP/www-community/blob/master/_data/tools.json but rather as it comes

**Comment by kingthorin** [comment]
Fair enough, I can sort it another day :wink:

**Review by kingthorin — APPROVED** [review]

**Comment by noraj** [comment]
> Fair enough, I can sort it another day wink

A run of this https://ourcodeworld.com/articles/read/764/how-to-sort-alphabetically-an-array-of-objects-by-key-in-javascript should be enough

**Comment by kingthorin** [comment]
I think I've used this in the past for other projects:
https://codeshack.io/json-sorter/

Lots of options. Thanks for your contribs.

**Pull request merged**
