### PR TITLE
Update Free_for_Open_Source_Application_Security_Tools.md

### PR DESCRIPTION
**Pull request by daudmalik06**
updates Vulert Description.

### CODE REVIEW

**Comment by psiinon** [comment]
This looks too much os a selling job to me...

**Comment by daudmalik06** [comment]
Hey @psiinon , thanks for feedback,  do you want me to remove some links or remove some specific text from description ?

**Comment by psiinon** [comment]
I think all entries on this page should be as factual as possible and not include phrases like "one of the most advanced open-source vulnerability databases available".
But the whole section sounds like marketing, I think the previous wording was much better.
Others may disagree with me 😁

**Comment by daudmalik06** [comment]
@psiinon i think what you suggest makes sense to make this whole page marketing neutral, let me do the changes accordingly.

**Comment by daudmalik06** [comment]
@psiinon  done, please review now. thanks again.

**Comment by psiinon** [comment]
Still a touch of marketting, but much better 😉 
Be interesting to get some other feedback..

**Comment by daudmalik06** [comment]
let me ask chat (gpt) if he can detect marketing from this text 😆

**Comment by daudmalik06** [comment]
@psiinon anyway, i will appreciate you suggestions, what do you think, should be removed. ?

**Comment by kingthorin** [comment]
I don't want to get nitpicky as I'm looking at this addition in isolation (not going back k to read other entries). But for my 2cents the second bullet could be dropped. (The DB one)

**Comment by daudmalik06** [comment]
@kingthorin @psiinon  done, removed complete DB information.

**Review by kingthorin — APPROVED** [review]
LGTM

**Pull request merged**
