### PR TITLE
Add output interoperability information for source code analysis tools

### PR DESCRIPTION
**Pull request by zbraiterman**
Reference OASIS SARIF standard in the `Important Selection Criteria` section.

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Weren’t the picky and rips changes in another PR?

**Comment by zbraiterman** [comment]
> Weren’t the pixy and rips changes in another PR?

Yes.  That as a PR for the "Static Code Analysis" page ( https://github.com/OWASP/www-community/blob/master/pages/controls/Static_Code_Analysis.md ), within the "controls" directory.  I felt that the SARIF reference would fit better as part of the "Source Code Analysis Tools" page ( https://github.com/OWASP/www-community/blob/master/pages/Source_Code_Analysis_Tools.md ).

**Comment by kingthorin** [comment]
Okay, this PR seems to contain both for some reason. I’ll see if I can fix it.

**Comment by zbraiterman** [comment]
> Okay, this PR seems to contain both for some reason. I’ll see if I can fix it.

Sorry about that.  I'm happy to create a new branch, and re-submit the PR from there, if you'd like.

**Pull request closed without merging**
