### PR TITLE
docs(pages-initiatives): the handler roadmap content

### PR DESCRIPTION
**Pull request by raphaelmoreira**
# About the content
The philosophy behind this content is to create a learning path and best practices in security, evolving with each act to focus on a specific aspect. To encourage the consumption of this content, I based it on the [Internet Storm Center](https://isc.sans.edu/handler_list.html) program, which emphasizes volunteering by security professionals. In other words: you can become one too.

Considering that OWASP Pages has a lot of content, I decided to start this project to condense all the knowledge, attempting to create a chronological journey. After all, there is already a lot of branched content, and the idea is to organize and centralize things.

In this first PR, I’m adding the homepage (prologue with context) and the first act, which talks about response headers.

>_Note: Although there is no defined standard, I took the liberty of creating a Brazilian Portuguese (pt-Br) version and appropriately directing the links. If this type of action is not permitted, please let me know so I can remove it and keep it only in `en-us`_.

Thank you.

### CODE REVIEW

**Comment by kingthorin** [comment]
If you're starting a project you should properly apply and get a project site.

**Comment by raphaelmoreira** [comment]
What would a "_project site_" be? Are you referring to something within the **OWASP Community**, or are you suggesting that I create something on my own, like a personal website?

I ask this because I thoroughly analyzed the existing content within `pages` repo before making my suggestion. And it seems to me that the information I’m proposing isn’t very different from what exists today. It’s an article like the others, but it’s structured in a way to expand the content.

In the root of `pages`, we have a collection of uncategorized articles (F_AQ, error handling, specific ASP.NET items_); others with information of little value (_just redirects_). And not all of them are visible on the main site at `https://owasp.org/www-community`. Although they all talk about the same subject (_security_), their use isn’t very organic.

Additionally, they are all unstandardized in terms of formatting (_font, examples, titles_).

Since we have the categories "Controls," "Attack," "Vulnerabilities," and "Others," I believe my proposed article would fit well under "Initiatives," as it aims to consolidate the content into a better-structured roadmap. As a bonus, I’m also reviewing everything that’s been written so far (_and I’ve updated a few, in fact_).

Wouldn’t it be worth reconsidering?

**Comment by kingthorin** [comment]
Like any of the organization's existing www-project-* repos.

To start a new project goto contact.owasp.org create an account and fill in the appropriate ticket template.

**Comment by raphaelmoreira** [comment]
Understood. Well, I will delete this pull request.

But one more question (for the future): soon I will review all the articles of 'pages', updating content e adding fresh info.

Can I do a "brazilian portuguese" version, like I did in this pull request? It is allowed?

**Comment by kingthorin** [comment]
Don't delete the content, I'm only one opinion 🤷‍♂️

I don't see anything wrong with adding content in other languages.  OWASP is a global organization. The only catch will be that content will diverge over time because there is an imbalance in contributor languages... as things currently stand people are more likely to update English content.

**Comment by raphaelmoreira** [comment]
Well, in this case, I will keeping an eye on changes to the English content (a track change on everything under 'pages').

If there are changes to something that has already been translated, I'll sync it.

We can leave a note in the translated content, or work with a review date, for example.

I understand that the more files there are, the more laborious the maintenance will be.

But maybe this way, it will encourage more Brazilians to contribute to OWASP.

**Comment by raphaelmoreira** [comment]
If the pull request proposal is accepted, I thought of the following change:

# Folder structure for language
Create a specific folder for each culture:

```
isc_handler_roadmap
|_acts
|   |_pt-br
|      |_prologue.md
|      |_act_1.md
|   prologue.md
|   act_1.md
|_home
    |_pt-br
       |_index.md
    index.md
```

# Note about translation
In the `www-community/index.md` file, add a topic "Translation" that states:

If you include, modify, or remove content from any file whose structure contains translations - _identifiable by the existence of "language-region" folders (e.g., `pt-br`)_ -, open a translation issue, so the adaptation can be made.

**Comment by mamicidal** [comment]
Hi Raphael - I think the best way forward is to request a new project. You can do that here: https://owasp.org/projects/ on the right menu > Start a New Project.  Your project might actually be a fit for an existing one (OWASP-Nest) in the stepped, chronologically sound approach for newcomers but we don't track this type of idea without a ticket. Please submit the New Project Request and I will work with you from there. Thanks. Starr

**Pull request closed without merging**
