### PR TITLE
GSoC Five

### PR DESCRIPTION
**Pull request by kingthorin**
- Permalink all the things  :+1:
- Add info.md to both areas.
- Add 2017 & 2018 info.

Fixes owasp/www-community#1

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping

**Comment by kingthorin** [comment]
Linking didn't pan out as expected, will submit a fix PR shortly.

**Comment by hblankenship** [comment]
I think it will work if you make the links initiatives/gsoc/gsoc2019 (drop
the initial /).

Regards,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

**Comment by kingthorin** [comment]
Yup that's what the issue was :+1:

**Pull request merged**
