### PR TITLE
Addition of a Checklist - Create The Essential Security Checklist for…

### PR DESCRIPTION
**Pull request by SNCherry**
… Software Development

### CODE REVIEW

**Comment by kingthorin** [comment]
I'd suggest submitting this to the cheat sheet series project.

https://owasp.org/www-project-cheat-sheets/

Or maybe one of the dev guide type projects.

**Comment by mtesauro** [comment]
FWIW, I agree with @kingthorin that this would make a great cheat sheet and likely get way more attention there then as a community contributed page since cheat sheets are already focused on developers.

**Comment by SNCherry** [comment]
> I'd suggest submitting this to the cheat sheet series project.
> 
> https://owasp.org/www-project-cheat-sheets/
> 
> Or maybe one of the dev guide type projects.
...
> FWIW, I agree with @kingthorin that this would make a great cheat sheet and likely get way more attention there then as a community contributed page since cheat sheets are already focused on developers.
---
Thats great - I didn't know that was a thing. Will do!

**Comment by kingthorin** [comment]
Closing, to be submitted to CS or other project.

**Pull request closed without merging**
