### PR TITLE
Reinstate RRM with disclaimer and additional refs

### PR DESCRIPTION
**Pull request by kingthorin**
Per discussion on: https://github.com/OWASP/www-community/pull/433

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
@avidouglen how does this look/seem?

image

**Comment by avidouglen** [comment]
I like it, thanks @kingthorin ! 
I still don't think RAF is really relevant, as its positioned as a SAST and not about rating risks, but as "additional resources" I'd say it's fine. 

My only other comment would likely be falling back into that same debate, but I dont think those other mature methodologies, as well as CVSS, are a good fit for developers trying to figure out how to prioritize things quickly and as part of their development workflow... But I wont say more so that I don't dig into that debate ;-)

**Comment by kingthorin** [comment]
I’ll have another look at raf and related content, I’ll also dig for Mozilla’s rapid risk assessment info and add something.

**Comment by kingthorin** [comment]
@avidouglen I dropped the RAF stuff, good call on that, and I did find/add Mozilla RRA info:
image

**Comment by kingthorin** [comment]
I’m gonna assume this is headed in an agreeable direction and merge, if you have further thoughts lemme know 🙂

**Comment by avidouglen** [comment]
@kingthorin fantastic, thanks. Really good call on the Mozilla RRA - still not quite the replacement I'd be looking for, but could serve the purpose for many cases.

**Pull request merged**
