### PR TITLE
Update Fuzzing.md

### PR DESCRIPTION
**Pull request by justanothernate**
https://owasp.org/www-community/OWASP_Testing_Guide_Appendix_C:_Fuzz_Vectors is a broken link so replaced with https://owasp.org/www-project-web-security-testing-guide/stable/6-Appendix/C-Fuzz_Vectors

### CODE REVIEW

**Comment by kingthorin** [comment]
Please see: https://owasp.org/www-project-web-security-testing-guide/#linking and update this to use a versioned link. Stable is only "stable" until the next release 😉

**Comment by kingthorin** [comment]
Please see: https://owasp.org/www-project-web-security-testing-guide/#linking and update this to use a versioned link. Stable is only "stable" until the next release 😉

**Comment by justanothernate** [comment]
Thanks, updated.

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
