### PR TITLE
Update Component_Analysis.md

### PR DESCRIPTION
**Pull request by jakircdai**
Added CloudDefense.AI on Tools Listing

### CODE REVIEW

**Review by kingthorin — CHANGES_REQUESTED** [review]
Please add it alphabetically

**Comment by kingthorin** [comment]
> Please add it alphabetically

**Comment by jakircdai** [comment]
> > Please add it alphabetically

@kingthorin Kindly check now. I have updated

**Comment by kingthorin** [comment]
I'll fix it in a few days

**Pull request closed without merging**
