### PR TITLE
Update tools.json

### PR DESCRIPTION
**Pull request by robert-apisec**
Link to new page

### CODE REVIEW

**Review by psiinon — CHANGES_REQUESTED** [review]
Change requested - undo :D

**Comment by robert-apisec** [comment]
Understood, and please forgive the oversight. I'm new at this, and was
trying to figure out how much traffic was coming from the owasp site -- but
absolutely NOT to track any individuals. My boss had asked me to figure out
where our website traffic was originating from, and this was the first way
I found when I Googled how to try and analyze traffic.

No offense intended; I hope none was taken. Won't happen again, and thanks
for bringing this to my attention.

**Comment by kingthorin** [comment]
No offense at all. Thanks for your understanding.

**Comment by robert-apisec** [comment]
Cool! Thank you so much, and please let me know if there's anything I can
do for you all. You provide such a great service to the community!

**Pull request closed without merging**
