### PR TITLE
Redirecting threat model pages

### PR DESCRIPTION
**Pull request by avidouglen**

### CODE REVIEW

**Comment by avidouglen** [comment]
Moving all TM content to centralised TM project

**Comment by kingthorin** [comment]
The TM project seems too immature. Much of the content on that project page is still based on ZAP and links nowhere. Plus there’s already a PR open reworking all the TM content.

**Comment by kingthorin** [comment]
The TM project is also questionably active https://github.com/OWASP/www-project-threat-model/issues/1

**Comment by avidouglen** [comment]
Right, it is currently being rebooted and is intended (amongst other purposes) to collect and resolve all the various conflicting resources OWASP currently has on Threat Modeling. 
Not really sure what you mean about ZAP or flagship though?

**Pull request closed without merging**
