### PR TITLE
Add GraphQL.security, OpenAPI.security and Escape Scanners

### PR DESCRIPTION
**Pull request by glimow**

### CODE REVIEW

**Comment by kingthorin** [comment]
@mtesauro thoughts on this? Are the three sufficiently different to list one vendor multiple times?

**Comment by mtesauro** [comment]
To be honest, what's in those 3 entries as best I can tell is:
(1) A commercial tool for API Security
(2) A Freemium tool for API Security (GraphQL) that links back to (1)
(3) A Freemium tool for API Security (REST/OAS) that links back to (1)

I have no problem with vendors doing free versions or otherwise limited and $0 versions on their core tech but it doesn't really warrant having 3 entries for what is a API Security tool and 2 variations of that tool.

I think the better approach is to keep the Escape entry and add links to the other two in the 'Note:' section like the links in the Zap and Burpsuite 'Note:' sections that point to further information/resources.

**Comment by glimow** [comment]
Hey @mtesauro @kingthorin, thanks for your feedback. I merged the three projects into one section.

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks @glimow. @mtesauro please feel free to approve/merge.

**Comment by mtesauro** [comment]
Looks good to me.  Thanks for the updates @glimow

**Pull request merged**
