### PR TITLE
CSRF - Readme file

### PR DESCRIPTION
**Pull request by Tholkappiar**
Hello, Maintainers!

I hope you are doing well. I've submitted a pull request by creating a Readme file about CSRF ( Cross-site request forgery ).

I wanted to let you know that I am open to making any necessary changes or improvements according to your suggestions. Please feel free to review my changes and provide any feedback you may have.

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards,
Tholkappiar

### CODE REVIEW

**Comment by kingthorin** [comment]
https://github.com/OWASP/www-community/blob/master/pages/attacks/cross-site-request-forgery.md
https://owasp.org/www-community/attacks/csrf

**Comment by Tholkappiar** [comment]
Oops ! Any other Topics which are required for the community . Please Let me Know ! I'll look into it .

Thank You !

**Comment by Tholkappiar** [comment]
Can I write about Follina Vulnerability ? if that is already contributed or exist , give some ideas on the Topic which I can contribute to the community .

Thank You.

**Comment by kingthorin** [comment]
I don’t think we have any other specific CVE write-ups, but it’s community content so if you think it is of benefit to OWASP’s audience then you can write about anything you like. (Just make sure you search first…. If you see something to change or improve with the existing CSRF content then go for it. Also FYI if your the author you don’t need to add yourself as contributor as well 😉)

**Comment by Tholkappiar** [comment]
Thank you for your time and consideration. I'll look forward into it.

**Pull request closed without merging**
