### PR TITLE
Add GSoC 2021 main and idea pages

### PR DESCRIPTION
**Pull request by bkimminich**

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Thanks for tackling this.

Could you properly format the front matter in both files?

**Comment by kingthorin** [comment]
Could you also update https://github.com/OWASP/www-community/blob/master/pages/initiatives/gsoc/index.md ?

**Comment by bkimminich** [comment]
Ah, my Markdown plugin messed up the frontmatter because I forgot to tick some checkbox again... 🤦  ... On it. And also the index page...

**Comment by bkimminich** [comment]
Done.

**Review by kingthorin — APPROVED** [review]
Thanks

**Comment by kingthorin** [comment]
FYI: https://github.com/OWASP/owasp.github.io/pull/134

**Pull request merged**
