### PR TITLE
added Salt Security to list of tools

### PR DESCRIPTION
**Pull request by yaronatsalt**
We would like Salt Security to be added to the list of API security tools

### CODE REVIEW

**Comment by kingthorin** [comment]
@mtesauro good with this?

**Comment by mtesauro** [comment]
I was putting them in alphabetical order (with numbers at the bottom) so it would be nice if it was in alpha order but I can always shift it around in my next PR.

I was given another tool on OWASP Slack so there's another PR coming shortly so we can merge as is and I'll fix the alpha order in my next PR or this one can be updated.  Either way, I'm fine with the additions as the end goal is as complete a list of tools as is possible.

**Comment by mtesauro** [comment]
@yaronatsalt Do you mind putting your addition in alpha order (see my previous comment)?

If not, no biggie, I can adjust it in my next PR.

**Comment by yaronatsalt** [comment]
Thanks for the quick response @mtesauro!
Placed Salt Security in the right place alphabetically

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thank you both!

**Pull request merged**
